export type DrinkCategory = 'original' | 'ultra' | 'juice' | 'hydro' | 'rehab';

export interface RetailerPrice {
  retailer: string;
  pricePerCan: number;
  packSize: number;
  totalPrice: number;
  inStock: boolean;
  url: string;
}

export interface EnergyDrink {
  id: number;
  name: string;
  brand: string;
  variant: string;
  category: DrinkCategory;
  categoryLabel: string;
  sizeOz: number;
  caffeineContentMg: number;
  calories: number;
  sugarG: number;
  accentColor: string;
  retailers: RetailerPrice[];
}

export const drinks: EnergyDrink[] = [
  {
    id: 1,
    name: 'Monster Original',
    brand: 'Monster Energy',
    variant: 'Green',
    category: 'original',
    categoryLabel: 'Original',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 210,
    sugarG: 54,
    accentColor: '#39d353',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.65, packSize: 48, totalPrice: 79.20, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.58, packSize: 24, totalPrice: 61.98, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.48, packSize: 1, totalPrice: 2.48, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.49, packSize: 1, totalPrice: 2.49, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.19, packSize: 1, totalPrice: 3.19, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.49, packSize: 1, totalPrice: 3.49, inStock: true, url: '#' },
    ],
  },
  {
    id: 2,
    name: 'Monster Ultra White',
    brand: 'Monster Energy',
    variant: 'Ultra White',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#e8e8e8',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.72, packSize: 48, totalPrice: 82.56, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.62, packSize: 24, totalPrice: 62.88, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.52, packSize: 1, totalPrice: 2.52, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.59, packSize: 1, totalPrice: 2.59, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.29, packSize: 1, totalPrice: 3.29, inStock: false, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.59, packSize: 1, totalPrice: 3.59, inStock: true, url: '#' },
    ],
  },
  {
    id: 3,
    name: 'Monster Ultra Paradise',
    brand: 'Monster Energy',
    variant: 'Ultra Paradise',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#00e5a0',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.72, packSize: 48, totalPrice: 82.56, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.65, packSize: 24, totalPrice: 63.60, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.56, packSize: 1, totalPrice: 2.56, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.59, packSize: 1, totalPrice: 2.59, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.29, packSize: 1, totalPrice: 3.29, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.59, packSize: 1, totalPrice: 3.59, inStock: false, url: '#' },
    ],
  },
  {
    id: 4,
    name: 'Monster Ultra Sunrise',
    brand: 'Monster Energy',
    variant: 'Ultra Sunrise',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ff8c00',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.72, packSize: 48, totalPrice: 82.56, inStock: false, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.70, packSize: 24, totalPrice: 64.80, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.58, packSize: 1, totalPrice: 2.58, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.69, packSize: 1, totalPrice: 2.69, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.39, packSize: 1, totalPrice: 3.39, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
    ],
  },
  {
    id: 5,
    name: 'Monster Ultra Fiesta',
    brand: 'Monster Energy',
    variant: 'Ultra Fiesta Mango',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ffe033',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.75, packSize: 48, totalPrice: 84.00, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.70, packSize: 24, totalPrice: 64.80, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.58, packSize: 1, totalPrice: 2.58, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.69, packSize: 1, totalPrice: 2.69, inStock: false, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.39, packSize: 1, totalPrice: 3.39, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
    ],
  },
  {
    id: 6,
    name: 'Monster Ultra Watermelon',
    brand: 'Monster Energy',
    variant: 'Ultra Watermelon',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ff4d6d',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.75, packSize: 48, totalPrice: 84.00, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.75, packSize: 24, totalPrice: 66.00, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.62, packSize: 1, totalPrice: 2.62, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.69, packSize: 1, totalPrice: 2.69, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.39, packSize: 1, totalPrice: 3.39, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.79, packSize: 1, totalPrice: 3.79, inStock: true, url: '#' },
    ],
  },
  {
    id: 7,
    name: 'Monster Juiced',
    brand: 'Monster Energy',
    variant: 'Mango Loco',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 220,
    sugarG: 54,
    accentColor: '#ff6b1a',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.80, packSize: 48, totalPrice: 86.40, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.78, packSize: 24, totalPrice: 66.72, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.68, packSize: 1, totalPrice: 2.68, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.79, packSize: 1, totalPrice: 2.79, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.49, packSize: 1, totalPrice: 3.49, inStock: false, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.79, packSize: 1, totalPrice: 3.79, inStock: true, url: '#' },
    ],
  },
  {
    id: 8,
    name: 'Monster Pipeline Punch',
    brand: 'Monster Energy',
    variant: 'Pipeline Punch',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 230,
    sugarG: 56,
    accentColor: '#ff9933',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.80, packSize: 48, totalPrice: 86.40, inStock: false, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.80, packSize: 24, totalPrice: 67.20, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.72, packSize: 1, totalPrice: 2.72, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.79, packSize: 1, totalPrice: 2.79, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.49, packSize: 1, totalPrice: 3.49, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.89, packSize: 1, totalPrice: 3.89, inStock: true, url: '#' },
    ],
  },
  {
    id: 9,
    name: 'Monster Assault',
    brand: 'Monster Energy',
    variant: 'Assault',
    category: 'original',
    categoryLabel: 'Original',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 200,
    sugarG: 54,
    accentColor: '#cc0000',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.68, packSize: 48, totalPrice: 80.64, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.62, packSize: 24, totalPrice: 62.88, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.52, packSize: 1, totalPrice: 2.52, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.59, packSize: 1, totalPrice: 2.59, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.29, packSize: 1, totalPrice: 3.29, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.59, packSize: 1, totalPrice: 3.59, inStock: true, url: '#' },
    ],
  },
  {
    id: 10,
    name: 'Monster Lo-Carb',
    brand: 'Monster Energy',
    variant: 'Lo-Carb Blue',
    category: 'original',
    categoryLabel: 'Original',
    sizeOz: 16,
    caffeineContentMg: 140,
    calories: 50,
    sugarG: 6,
    accentColor: '#4488ff',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.68, packSize: 48, totalPrice: 80.64, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.62, packSize: 24, totalPrice: 62.88, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.52, packSize: 1, totalPrice: 2.52, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.59, packSize: 1, totalPrice: 2.59, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.19, packSize: 1, totalPrice: 3.19, inStock: false, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.49, packSize: 1, totalPrice: 3.49, inStock: true, url: '#' },
    ],
  },
  {
    id: 11,
    name: 'Monster Hydro',
    brand: 'Monster Energy',
    variant: 'Blue Ice',
    category: 'hydro',
    categoryLabel: 'Hydro',
    sizeOz: 20,
    caffeineContentMg: 125,
    calories: 25,
    sugarG: 6,
    accentColor: '#00aaff',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.95, packSize: 24, totalPrice: 46.80, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.95, packSize: 24, totalPrice: 70.80, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.88, packSize: 1, totalPrice: 2.88, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.99, packSize: 1, totalPrice: 2.99, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.99, packSize: 1, totalPrice: 3.99, inStock: true, url: '#' },
    ],
  },
  {
    id: 12,
    name: 'Monster Hydro',
    brand: 'Monster Energy',
    variant: 'Manic Melon',
    category: 'hydro',
    categoryLabel: 'Hydro',
    sizeOz: 20,
    caffeineContentMg: 125,
    calories: 30,
    sugarG: 6,
    accentColor: '#ff6b9d',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.95, packSize: 24, totalPrice: 46.80, inStock: false, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.98, packSize: 24, totalPrice: 71.52, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.88, packSize: 1, totalPrice: 2.88, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.99, packSize: 1, totalPrice: 2.99, inStock: false, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.99, packSize: 1, totalPrice: 3.99, inStock: true, url: '#' },
    ],
  },
  {
    id: 13,
    name: 'Monster Rehab',
    brand: 'Monster Energy',
    variant: 'Lemonade + Tea',
    category: 'rehab',
    categoryLabel: 'Rehab',
    sizeOz: 15.5,
    caffeineContentMg: 160,
    calories: 25,
    sugarG: 6,
    accentColor: '#e8d44d',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.78, packSize: 48, totalPrice: 85.44, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.72, packSize: 24, totalPrice: 65.28, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.58, packSize: 1, totalPrice: 2.58, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.69, packSize: 1, totalPrice: 2.69, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.39, packSize: 1, totalPrice: 3.39, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
    ],
  },
  {
    id: 14,
    name: 'Monster Rehab',
    brand: 'Monster Energy',
    variant: 'Peach + Tea',
    category: 'rehab',
    categoryLabel: 'Rehab',
    sizeOz: 15.5,
    caffeineContentMg: 160,
    calories: 25,
    sugarG: 6,
    accentColor: '#ffb347',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.78, packSize: 48, totalPrice: 85.44, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.75, packSize: 24, totalPrice: 66.00, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.62, packSize: 1, totalPrice: 2.62, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.69, packSize: 1, totalPrice: 2.69, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.39, packSize: 1, totalPrice: 3.39, inStock: false, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.69, packSize: 1, totalPrice: 3.69, inStock: true, url: '#' },
    ],
  },
  {
    id: 15,
    name: 'Monster Java',
    brand: 'Monster Energy',
    variant: 'Mean Bean',
    category: 'original',
    categoryLabel: 'Original',
    sizeOz: 15,
    caffeineContentMg: 188,
    calories: 200,
    sugarG: 26,
    accentColor: '#8B4513',
    retailers: [
      { retailer: 'Costco', pricePerCan: 1.92, packSize: 24, totalPrice: 46.08, inStock: true, url: '#' },
      { retailer: 'Amazon', pricePerCan: 2.92, packSize: 24, totalPrice: 70.08, inStock: true, url: '#' },
      { retailer: 'Walmart', pricePerCan: 2.78, packSize: 1, totalPrice: 2.78, inStock: true, url: '#' },
      { retailer: 'Target', pricePerCan: 2.89, packSize: 1, totalPrice: 2.89, inStock: true, url: '#' },
      { retailer: 'GNC', pricePerCan: 3.59, packSize: 1, totalPrice: 3.59, inStock: true, url: '#' },
      { retailer: '7-Eleven', pricePerCan: 3.89, packSize: 1, totalPrice: 3.89, inStock: true, url: '#' },
    ],
  },
];

export const navLinks = [
  { label: 'Products', href: '/' },
  { label: 'Best Deals', href: '/reportage' },
  { label: 'Price History', href: '/archive' },
  { label: 'About', href: '/about' },
];

export const retailers = ['Amazon', 'Walmart', 'Target', '7-Eleven', 'Costco', 'GNC'];
