export type DrinkCategory = 'original' | 'ultra' | 'juice' | 'hydro' | 'rehab' | 'java';

export interface RetailerPrice {
  retailer: string;
  pricePerCan: number;
  packSize: number;
  totalPrice: number;
  inStock: boolean;
  url: string;
}

export interface EnergyDrink {
  id: number;
  name: string;
  brand: string;
  variant: string;
  category: DrinkCategory;
  categoryLabel: string;
  sizeOz: number;
  caffeineContentMg: number;
  calories: number;
  sugarG: number;
  accentColor: string;
  image?: string;
  retailers: RetailerPrice[];
}

// Scraper IDs for live price fetching
export const scraperIds: Record<number, { woolworths?: number; colesPath?: string }> = {
  1:  { woolworths: 329812,  colesPath: 'monster-energy-drink-can-green-500ml-2787136' },
  2:  { woolworths: 489787,  colesPath: 'monster-energy-ultra-can-500ml-2787147' },
  3:  { woolworths: 62911,   colesPath: 'monster-ultra-paradise-can-500ml-3535285' },
  5:  { woolworths: 174492,  colesPath: 'monster-ultra-fiesta-mango-flavour-energy-drink-can-500ml-4402516' },
  7:  { woolworths: 698612,  colesPath: 'monster-energy-mango-loco-can-500ml-3290778' },
  8:  { woolworths: 803888,  colesPath: 'monster-pipeline-punch-can-500ml-3511469' },
  15: { woolworths: 318593,  colesPath: 'monster-java-iced-coffee-can-java-bean-305ml-7071539' },
  16: { woolworths: 317864,  colesPath: 'monster-java-iced-coffee-can-java-moca-305ml-7071540' },
  17: { woolworths: 220971,  colesPath: 'monster-energy-can-drink-ultra-gold-500ml-5155220' },
  18: { woolworths: 919631,  colesPath: 'monster-energy-drink-ultra-violet-can-500ml-8593020' },
  19: { woolworths: 6013090, colesPath: 'monster-energy-drink-ultra-ruby-red-500ml-9965141' },
  20: { woolworths: 6024547 },
  21: { woolworths: 6059029 },
  22: { woolworths: 6057776 },
  23: {                       colesPath: 'monster-energy-drink-ultra-vice-500ml-1308012' },
  24: {                       colesPath: 'monster-energy-drink-ultra-strawberry-can-500ml-7717127' },
  25: { woolworths: 391929,  colesPath: 'monster-energy-ultra-peachy-keen-can-500ml-6413422' },
};

// Monster Original first, then alphabetical by name
export const drinks: EnergyDrink[] = [
  {
    id: 1,
    name: 'Monster Original',
    brand: 'Monster Energy',
    variant: 'Green',
    category: 'original',
    categoryLabel: 'Original',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 210,
    sugarG: 54,
    accentColor: '#39d353',
    image: 'https://productimages.coles.com.au/productimages/2/2787136.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.69, packSize: 24, totalPrice: 40.56, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 20,
    name: 'Monster Aussie Lemonade',
    brand: 'Monster Energy',
    variant: 'Aussie Style Lemonade',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 220,
    sugarG: 52,
    accentColor: '#b8e04a',
    image: 'https://snackje.com/cdn/shop/files/Monster-Juiced-Aussie-Lemonade-500ml.png?v=1759761051',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.80, packSize: 24, totalPrice: 43.20, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 16,
    name: 'Monster Java Loca Mocha',
    brand: 'Monster Energy',
    variant: 'Loca Mocha',
    category: 'java',
    categoryLabel: 'Java',
    sizeOz: 15,
    caffeineContentMg: 188,
    calories: 230,
    sugarG: 28,
    accentColor: '#3a1a0a',
    image: 'https://productimages.coles.com.au/productimages/7/7071540.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 4.50, packSize: 1,  totalPrice: 4.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 4.50, packSize: 1,  totalPrice: 4.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.92, packSize: 24, totalPrice: 46.08, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 4.99, packSize: 1,  totalPrice: 4.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 15,
    name: 'Monster Java Mean Bean',
    brand: 'Monster Energy',
    variant: 'Mean Bean',
    category: 'java',
    categoryLabel: 'Java',
    sizeOz: 15,
    caffeineContentMg: 188,
    calories: 200,
    sugarG: 26,
    accentColor: '#8B4513',
    image: 'https://productimages.coles.com.au/productimages/7/7071539.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 4.50, packSize: 1,  totalPrice: 4.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 4.50, packSize: 1,  totalPrice: 4.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.92, packSize: 24, totalPrice: 46.08, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 4.99, packSize: 1,  totalPrice: 4.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 7,
    name: 'Monster Juiced',
    brand: 'Monster Energy',
    variant: 'Mango Loco',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 220,
    sugarG: 54,
    accentColor: '#ff6b1a',
    image: 'https://productimages.coles.com.au/productimages/3/3290778.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.80, packSize: 24, totalPrice: 43.20, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 21,
    name: 'Monster Juiced Rio Punch',
    brand: 'Monster Energy',
    variant: 'Rio Punch',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 220,
    sugarG: 52,
    accentColor: '#ff3030',
    image: 'https://www.bestwaywholesale.co.uk/img/products/1000/0/5056784900420.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.80, packSize: 24, totalPrice: 43.20, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 8,
    name: 'Monster Pipeline Punch',
    brand: 'Monster Energy',
    variant: 'Pipeline Punch',
    category: 'juice',
    categoryLabel: 'Juice',
    sizeOz: 16,
    caffeineContentMg: 160,
    calories: 230,
    sugarG: 56,
    accentColor: '#ff9933',
    image: 'https://productimages.coles.com.au/productimages/3/3511469.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.80, packSize: 24, totalPrice: 43.20, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 5,
    name: 'Monster Ultra Fiesta',
    brand: 'Monster Energy',
    variant: 'Ultra Fiesta Mango',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ffe033',
    image: 'https://productimages.coles.com.au/productimages/4/4402516.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.75, packSize: 24, totalPrice: 42.00, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 17,
    name: 'Monster Ultra Gold',
    brand: 'Monster Energy',
    variant: 'Ultra Gold',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ffd700',
    image: 'https://productimages.coles.com.au/productimages/5/5155220.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 25,
    name: 'Monster Ultra Peachy Keen',
    brand: 'Monster Energy',
    variant: 'Ultra Peachy Keen',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ffb347',
    image: 'https://productimages.coles.com.au/productimages/6/6413422.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 3,
    name: 'Monster Ultra Paradise',
    brand: 'Monster Energy',
    variant: 'Ultra Paradise',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#00e5a0',
    image: 'https://productimages.coles.com.au/productimages/3/3535285.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 19,
    name: 'Monster Ultra Ruby Red',
    brand: 'Monster Energy',
    variant: 'Ultra Ruby Red',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#dc143c',
    image: 'https://productimages.coles.com.au/productimages/9/9965141.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 24,
    name: 'Monster Ultra Strawberry Dreams',
    brand: 'Monster Energy',
    variant: 'Ultra Strawberry Dreams',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ff8fa3',
    image: 'https://productimages.coles.com.au/productimages/7/7717127.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 23,
    name: 'Monster Ultra Vice Guava',
    brand: 'Monster Energy',
    variant: 'Ultra Vice Guava',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ff69b4',
    image: 'https://productimages.coles.com.au/productimages/1/1308012.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 18,
    name: 'Monster Ultra Violet',
    brand: 'Monster Energy',
    variant: 'Ultra Violet',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#8b5cf6',
    image: 'https://productimages.coles.com.au/productimages/8/8593020.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 2,
    name: 'Monster Ultra White',
    brand: 'Monster Energy',
    variant: 'Ultra White',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#e8e8e8',
    image: 'https://productimages.coles.com.au/productimages/2/2787147.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: true,  url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
  {
    id: 22,
    name: 'Monster x Lando Norris',
    brand: 'Monster Energy',
    variant: 'Limited Edition',
    category: 'ultra',
    categoryLabel: 'Ultra',
    sizeOz: 16,
    caffeineContentMg: 150,
    calories: 10,
    sugarG: 0,
    accentColor: '#ff6900',
    image: 'https://cdn0.woolworths.media/content/wowproductimages/large/6057776.jpg',
    retailers: [
      { retailer: 'Woolworths',       pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: true,  url: '#' },
      { retailer: 'Coles',            pricePerCan: 5.50, packSize: 1,  totalPrice: 5.50,  inStock: false, url: '#' },
      { retailer: 'Costco Australia', pricePerCan: 1.72, packSize: 24, totalPrice: 41.28, inStock: false, url: '#' },
      { retailer: '7-Eleven',         pricePerCan: 5.99, packSize: 1,  totalPrice: 5.99,  inStock: true,  url: '#' },
    ],
  },
];

export const navLinks = [
  { label: 'Products', href: '/' },
  { label: 'Best Deals', href: '/reportage' },
  { label: 'Price History', href: '/archive' },
  { label: 'About', href: '/about' },
];

export const retailers = ['Woolworths', 'Coles', 'Costco Australia', '7-Eleven'];
